microarch_level:
  - 1
  - 3  # [unix and x86_64]
  - 4  # [unix and x86_64]

c_compiler:             # [osx]
  - clang               # [osx]
cxx_compiler:           # [osx]
  - clangxx             # [osx]
cxx_compiler_version:   # [osx]
  - 22                  # [osx]
